# Generated by Django 4.2.7 on 2023-12-10 20:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TypeCurrency",
            fields=[
                (
                    "type_currency_id",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("sort_order", models.IntegerField(blank=True, null=True)),
                ("code", models.CharField(max_length=3)),
                ("name", models.CharField(max_length=50)),
                ("country_name", models.CharField(max_length=50)),
                ("flag_url", models.CharField(max_length=300)),
                ("is_analysis", models.BooleanField()),
                ("is_spot_history", models.BooleanField()),
                ("is_fwd_efficiency", models.BooleanField()),
                ("is_fx_movement", models.BooleanField()),
            ],
            options={
                "db_table": "type_currency",
            },
        ),
        migrations.CreateModel(
            name="TypeStatus",
            fields=[
                (
                    "type_status_id",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=50)),
                ("color", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "type_status",
            },
        ),
        migrations.CreateModel(
            name="TypeTool",
            fields=[
                (
                    "type_tool_id",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("sort_order", models.IntegerField(blank=True, null=True)),
                ("name", models.CharField(max_length=50)),
                ("is_analysis_tool", models.BooleanField()),
                ("is_market_tool", models.BooleanField()),
                ("is_hedging_tool", models.BooleanField()),
            ],
            options={
                "db_table": "type_tool",
            },
        ),
    ]
