# Generated by Django 4.2.7 on 2024-01-30 13:41

from django.db import migrations


def update(*args):
    from api_gateway.models import TypeCurrency

    currencies = ["USD", "EUR", "GBP", "CHF", "JPY", "BRL", "COP", "MXN", "CAD", "CNY"]
    TypeCurrency.objects.all().update(sort_order=None)

    for index, value in enumerate(currencies):
        index += 1
        val = TypeCurrency.objects.get(code=value)
        val.sort_order = index
        val.save()


class Migration(migrations.Migration):
    dependencies = [
        ("api_gateway", "0002_populate_database"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="typecurrency",
            options={"ordering": ["sort_order", "code"]},
        ),
        migrations.RunPython(update),
    ]
