from .all_admin_organization_test import AllAdminOrganizationTest
from .create_admin_organization_test import CreateAdminOrganizationTest
from .detail_admin_organization_test import DetailAdminOrganizationTest
from .delete_admin_organization_test import DeleteAdminOrganizationTest
from .partial_update_admin_organization_test import PartialUpdateAdminOrganizationTest
from .update_admin_organization_test import UpdateAdminOrganizationTest

from .all_admin_user_test import AllAdminUserTest
from .create_admin_user_test import CreateAdminUserTest
from .delete_admin_user_test import DeleteAdminUserTest
from .detail_admin_user_test import DetailAdminUserTest
from .partial_update_admin_user_test import PartialUpdateAdminUserTest
from .update_admin_user_test import UpdateAdminUserTest
