# Generated by Django 4.2.7 on 2024-01-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hedge_simulation", "0002_hedgesimulation_result_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="hedgesimulation",
            name="end_date",
            field=models.DateField(default="2024-01-29"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hedgesimulation",
            name="start_date",
            field=models.DateField(default="2024-01-29"),
            preserve_default=False,
        ),
    ]
