# Generated by Django 4.2.7 on 2024-02-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "hedge_simulation",
            "0003_hedgesimulation_end_date_hedgesimulation_start_date",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hedgesimulation",
            options={"ordering": ["pin", "-date_updated"]},
        ),
        migrations.RemoveField(
            model_name="hedgesimulation",
            name="response",
        ),
        migrations.AddField(
            model_name="hedgesimulation",
            name="pin",
            field=models.BooleanField(default=False),
        ),
    ]
