# Generated by Django 4.2.7 on 2024-02-05 13:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hedge_simulation", "0004_alter_hedgesimulation_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hedgesimulation",
            options={"ordering": ["-pin", "-date_updated"]},
        ),
    ]
