# Generated by Django 4.2.7 on 2024-02-21 21:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hedge_simulation", "0005_alter_hedgesimulation_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="hedgesimulation",
            name="simulation_status",
            field=models.CharField(
                choices=[
                    ("ENQUEUED", "ENQUEUED"),
                    ("IN PROGRESS", "IN PROGRESS"),
                    ("COMPLETED", "COMPLETED"),
                    ("FAILED", "FAILED"),
                ],
                default="ENQUEUED",
            ),
        ),
    ]
