# Generated by Django 4.2.7 on 2024-02-16 04:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("api_gateway", "0003_alter_typecurrency_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FxCurrencyPair",
            fields=[
                (
                    "fx_currency_pair_id",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "base_currency",
                    models.ForeignKey(
                        db_column="base_currency_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="fxcurrency_base_currency_set",
                        to="api_gateway.typecurrency",
                    ),
                ),
                (
                    "foreign_currency",
                    models.ForeignKey(
                        db_column="foreign_currency_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="fxcurrency_foreign_currency_set",
                        to="api_gateway.typecurrency",
                    ),
                ),
            ],
            options={
                "db_table": "fx_currency_pair",
            },
        ),
        migrations.CreateModel(
            name="SpotHistory",
            fields=[
                (
                    "spot_history_id",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_default", models.BooleanField(default=False, editable=False)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("duration", models.IntegerField()),
                ("layered", models.BooleanField(default=True)),
                (
                    "base_currency",
                    models.ForeignKey(
                        db_column="base_currency_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="spothistory_base_currency_set",
                        to="api_gateway.typecurrency",
                    ),
                ),
                (
                    "foreign_currency",
                    models.ForeignKey(
                        db_column="foreign_currency_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="spothistory_foreign_currency_set",
                        to="api_gateway.typecurrency",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "spot_history",
                "ordering": ("-date_updated", "-date_added"),
            },
        ),
        migrations.CreateModel(
            name="FxMovement",
            fields=[
                (
                    "fx_movement_id",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_default", models.BooleanField(default=False, editable=False)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("duration", models.IntegerField()),
                (
                    "currency_pairs",
                    models.ManyToManyField(
                        db_column="fx_currency_pair_id", to="market.fxcurrencypair"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "fx_movement",
                "ordering": ("-date_updated", "-date_added"),
            },
        ),
        migrations.CreateModel(
            name="FwdEfficiency",
            fields=[
                (
                    "fwd_efficiency_id",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_default", models.BooleanField(default=False, editable=False)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("duration", models.IntegerField()),
                (
                    "base_currency",
                    models.ForeignKey(
                        db_column="base_currency_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="fwdefficiency_base_currency_set",
                        to="api_gateway.typecurrency",
                    ),
                ),
                (
                    "foreign_currency",
                    models.ForeignKey(
                        db_column="foreign_currency_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="fwdefficiency_foreign_currency_set",
                        to="api_gateway.typecurrency",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "fwd_efficiency",
                "ordering": ("-date_updated", "-date_added"),
            },
        ),
    ]
