# Generated by Django 4.2.7 on 2024-02-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "populate_roles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(max_length=20),
        ),
    ]
