# Generated by Django 4.2.7 on 2023-12-10 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api_gateway", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Analysis",
            fields=[
                (
                    "analysis_id",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=100)),
                (
                    "base_currency",
                    models.ForeignKey(
                        db_column="base_currency_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="analysis_base_currency_set",
                        to="api_gateway.typecurrency",
                    ),
                ),
                (
                    "foreign_currency",
                    models.ForeignKey(
                        db_column="term_currency_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="analysis_term_currency_set",
                        to="api_gateway.typecurrency",
                    ),
                ),
            ],
            options={
                "db_table": "analysis",
            },
        ),
        migrations.CreateModel(
            name="TypeAnalysisRole",
            fields=[
                (
                    "type_analysis_role_id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=50)),
                ("level", models.IntegerField()),
                ("description", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "type_analysis_role",
            },
        ),
        migrations.CreateModel(
            name="TypeCategory",
            fields=[
                (
                    "type_category_id",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "type_category",
            },
        ),
        migrations.CreateModel(
            name="SimulationEnviroment",
            fields=[
                (
                    "simulation_environment_id",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=50)),
                ("volatility", models.FloatField()),
                ("skew", models.FloatField()),
                ("appreciation_percent", models.FloatField()),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="analysis.analysis",
                    ),
                ),
            ],
            options={
                "db_table": "simulation_environment",
            },
        ),
        migrations.AddField(
            model_name="analysis",
            name="type_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="analysis.typecategory",
            ),
        ),
        migrations.AddField(
            model_name="analysis",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
