# Generated by Django 4.2.7 on 2023-12-12 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api_gateway", "0002_populate_database"),
        ("analysis", "0002_populate_database"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysis",
            name="base_currency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="analysis_base_currency_set",
                to="api_gateway.typecurrency",
            ),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="foreign_currency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="analysis_foreign_currency_currency_set",
                to="api_gateway.typecurrency",
            ),
        ),
    ]
