# Generated by Django 4.2.7 on 2024-01-25 13:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0004_analysis_organization"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="simulationenviroment",
            name="analysis",
        ),
        migrations.AlterField(
            model_name="simulationenviroment",
            name="appreciation_percent",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(-1.0),
                    django.core.validators.MaxValueValidator(1.0),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="simulationenviroment",
            name="skew",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(-0.1),
                    django.core.validators.MaxValueValidator(0.1),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="simulationenviroment",
            name="volatility",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ]
            ),
        ),
    ]
