# Generated by Django 4.2.7 on 2024-01-30 15:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0005_remove_simulationenviroment_analysis_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="analysis",
            options={"ordering": ("date_updated", "date_added")},
        ),
    ]
