# Generated by Django 4.2.7 on 2023-12-10 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("analysis", "0001_initial"),
        ("api_gateway", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomStrategy",
            fields=[
                (
                    "custom_strategy_id",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=300)),
                (
                    "created_by_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "custom_strategy",
            },
        ),
        migrations.CreateModel(
            name="CustomStrategyLeg",
            fields=[
                (
                    "custom_strategy_leg_id",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_call", models.BooleanField()),
                ("is_bought", models.BooleanField()),
                ("premium", models.DecimalField(decimal_places=2, max_digits=1000)),
                ("leverage", models.FloatField()),
                ("strike", models.FloatField(blank=True, null=True)),
                ("barrier_type", models.CharField(blank=True, max_length=8, null=True)),
                ("barrier_level", models.FloatField(blank=True, null=True)),
                (
                    "custom_strategy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="custom_strategy_leg",
                        to="strategy_simulation.customstrategy",
                    ),
                ),
            ],
            options={
                "db_table": "custom_strategy_leg",
            },
        ),
        migrations.CreateModel(
            name="TypeDefaultStrategy",
            fields=[
                (
                    "type_default_strategy_id",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("sort_order", models.IntegerField(blank=True, null=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=250)),
                ("image_url", models.CharField(max_length=250)),
            ],
            options={
                "db_table": "type_default_strategy",
            },
        ),
        migrations.CreateModel(
            name="TypeDefaultStrategyLeg",
            fields=[
                (
                    "type_default_strategy_leg_id",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("sort_order", models.IntegerField(blank=True, null=True)),
                ("image_url", models.CharField(max_length=255)),
                ("is_call", models.BooleanField(blank=True, null=True)),
                ("is_bought", models.BooleanField()),
                ("premium", models.DecimalField(decimal_places=2, max_digits=1000)),
                ("leverage", models.FloatField()),
                ("strike", models.FloatField()),
                ("barrier_type", models.CharField(blank=True, max_length=8, null=True)),
                ("barrier_level", models.FloatField(blank=True, null=True)),
                (
                    "type_default_strategy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="type_default_strategy_leg",
                        to="strategy_simulation.typedefaultstrategy",
                    ),
                ),
            ],
            options={
                "db_table": "type_default_strategy_leg",
            },
        ),
        migrations.CreateModel(
            name="StrategySimulation",
            fields=[
                (
                    "strategy_simulation_id",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_saved", models.BooleanField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("notional", models.DecimalField(decimal_places=2, max_digits=1000)),
                ("spot_rate_override", models.FloatField(blank=True, null=True)),
                ("forward_rate_override", models.FloatField(blank=True, null=True)),
                ("is_base_sold", models.BooleanField()),
                ("initial_spot_rate", models.FloatField()),
                ("initial_forward_rate", models.FloatField()),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="strategy_simulation",
                        to="analysis.analysis",
                    ),
                ),
                (
                    "simulation_environment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="analysis.simulationenviroment",
                    ),
                ),
                (
                    "type_status",
                    models.ForeignKey(
                        default="6f3d8caa-ca80-4117-8d03-c487c43338bc",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api_gateway.typestatus",
                    ),
                ),
            ],
            options={
                "db_table": "strategy_simulation",
            },
        ),
        migrations.CreateModel(
            name="StrategyInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "premium_override",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=1000, null=True
                    ),
                ),
                ("leverage_override", models.FloatField(blank=True, null=True)),
                ("strike_override", models.FloatField(blank=True, null=True)),
                ("instance_group", models.IntegerField()),
                (
                    "custom_strategy_leg",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="strategy_simulation.customstrategyleg",
                    ),
                ),
                (
                    "strategy_simulation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="strategy_instance",
                        to="strategy_simulation.strategysimulation",
                    ),
                ),
                (
                    "type_default_strategy_leg",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="strategy_simulation.typedefaultstrategyleg",
                    ),
                ),
            ],
            options={
                "db_table": "strategy_instance",
            },
        ),
    ]
