# Generated by Django 4.2.7 on 2023-12-29 00:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("strategy_simulation", "0004_remove_strategysimulation_is_saved"),
    ]

    operations = [
        migrations.AddField(
            model_name="strategysimulation",
            name="name",
            field=models.CharField(default="Strategy Simulation", max_length=100),
            preserve_default=False,
        ),
    ]
