# Generated by Django 4.2.7 on 2024-01-22 19:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("strategy_simulation", "0009_populate_database"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customstrategyleg",
            name="custom_strategy",
        ),
        migrations.RemoveField(
            model_name="typedefaultstrategyleg",
            name="type_default_strategy",
        ),
        migrations.AlterField(
            model_name="strategyinstance",
            name="leverage_override",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="strategyinstance",
            name="premium_override",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=1000,
                null=True,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AlterField(
            model_name="strategyinstance",
            name="strike_override",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-100.0),
                    django.core.validators.MaxValueValidator(100.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="strategyleg",
            name="leverage",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="strategyleg",
            name="premium",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=1000,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AlterField(
            model_name="strategyleg",
            name="strike",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-100.0),
                    django.core.validators.MaxValueValidator(100.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="strategysimulation",
            name="notional",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=1000,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AlterField(
            model_name="strategysimulation",
            name="spread",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ]
            ),
        ),
        migrations.DeleteModel(
            name="CustomStrategy",
        ),
        migrations.DeleteModel(
            name="CustomStrategyLeg",
        ),
        migrations.DeleteModel(
            name="TypeDefaultStrategy",
        ),
        migrations.DeleteModel(
            name="TypeDefaultStrategyLeg",
        ),
    ]
