# Generated by Django 4.2.7 on 2024-01-24 22:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "strategy_simulation",
            "0010_remove_customstrategyleg_custom_strategy_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="strategyleg",
            name="barrier_level",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-100.0),
                    django.core.validators.MaxValueValidator(100.0),
                ],
            ),
        ),
    ]
