# Generated by Django 4.2.7 on 2024-02-05 13:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("strategy_simulation", "0014_alter_strategysimulation_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="strategysimulation",
            options={"ordering": ["-pin", "-date_updated"]},
        ),
    ]
