# Generated by Django 4.2.7 on 2024-02-13 13:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("strategy_simulation", "0013_populate_strategy_leg"),
        ("strategy_simulation", "0015_alter_strategysimulation_options"),
    ]

    operations = []
