# Generated by Django 4.2.7 on 2024-02-13 22:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.RunSQL(
            sql=[("DROP TABLE IF EXISTS spot_history_data;")],
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.CreateModel(
            name="SpotHistoryData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("currency", models.CharField(max_length=3)),
                ("rate", models.DecimalField(decimal_places=6, max_digits=18)),
            ],
            options={
                "db_table": "spot_history_data",
                "indexes": [
                    models.Index(fields=["date"], name="spot_histor_date_4e10b5_idx"),
                    models.Index(
                        fields=["date", "currency"], name="spot_histor_date_655ad1_idx"
                    ),
                ],
                "unique_together": {("date", "currency")},
            },
        ),
    ]
