# Generated by Django 4.2.7 on 2024-02-14 04:27

import os
from django.db import migrations, connection

from api_gateway.settings.config import DJANGO_TESTING


def load_data_from_csv(*args, **kwargs):
    if DJANGO_TESTING:
        print("Skipping spot history data import during tests")
        return

    file_path = os.path.join(
        os.path.dirname(__file__), "..", "utils", "spot_history_data.csv"
    )
    with open(file_path, "r") as file:
        with connection.cursor() as cursor:
            copy_sql = """
                COPY public.spot_history_data (date, currency, rate) FROM stdin WITH (FORMAT csv, DELIMITER E'\t');
            """
            print("Importing spot history data from csv")
            cursor.copy_expert(copy_sql, file)
            print("Done importing")


class Migration(migrations.Migration):
    dependencies = [
        ("time_series", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(load_data_from_csv),
    ]
