# Generated by Django 4.2.7 on 2023-12-10 20:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("strategy_simulation", "0001_initial"),
        ("analysis", "0001_initial"),
        ("api_gateway", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarginSimulation",
            fields=[
                (
                    "margin_simulation_id",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "minimum_transfer_amount",
                    models.DecimalField(decimal_places=2, max_digits=1000),
                ),
                ("initial_margin_percentage", models.FloatField()),
                ("variation_margin_percentage", models.FloatField()),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="analysis.analysis",
                    ),
                ),
                (
                    "strategy_simulation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="strategy_simulation.strategysimulation",
                    ),
                ),
                (
                    "type_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api_gateway.typestatus",
                    ),
                ),
            ],
            options={
                "db_table": "margin_simulation",
            },
        ),
    ]
