# Generated by Django 4.2.7 on 2023-12-29 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0003_alter_analysis_base_currency_and_more"),
        ("margin_simulation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="marginsimulation",
            name="name",
            field=models.CharField(default="Margin Simulation", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="marginsimulation",
            name="analysis",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="margin_simulation",
                to="analysis.analysis",
            ),
        ),
    ]
