# Generated by Django 4.2.7 on 2024-01-22 19:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("margin_simulation", "0002_marginsimulation_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marginsimulation",
            name="initial_margin_percentage",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(0.001),
                    django.core.validators.MaxValueValidator(1.0),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="marginsimulation",
            name="minimum_transfer_amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=1000,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AlterField(
            model_name="marginsimulation",
            name="variation_margin_percentage",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(0.001),
                    django.core.validators.MaxValueValidator(1.0),
                ]
            ),
        ),
    ]
