# Generated by Django 4.2.7 on 2024-02-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("margin_simulation", "0004_marginsimulation_result_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="marginsimulation",
            options={"ordering": ["pin", "-date_updated"]},
        ),
        migrations.AddField(
            model_name="marginsimulation",
            name="pin",
            field=models.BooleanField(default=False),
        ),
    ]
