# Generated by Django 4.2.7 on 2024-02-05 13:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "margin_simulation",
            "0005_alter_marginsimulation_options_marginsimulation_pin",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="marginsimulation",
            options={"ordering": ["-pin", "-date_updated"]},
        ),
    ]
